### PR TITLE
Valkyrie dive stuck workaround

### LINKED ISSUE #121: Valkyrie launch ability sound won't stop after landing.
It's also way too loud compared to the rest of the game, it makes my head hurt :/

### PR DESCRIPTION
**Pull request by RDaneliya**
Changed condition checking if dive event should be finished.
Dunno if it's correct way. That's literally first time I touch minecraft mods

### CODE REVIEW

**Comment by muon-rw** [comment]
I'm curious why you think this would resolve the issue, or how this would even be a good idea? 

If a player is above a block that isn't movement blocking, like a floating torch, that would mean they're still in the air. This would fire the ability prematurely.

Regardless, landing on any movement blocking block at any point should stop the sound whenever that happens, so I suspect the actual issue here is an underlying bug in Origins:
1. `rising_action` not firing 100% consistently, or 
2. a rare power sync/registry issue causing the land power not to load at all.

Maybe a fallback recurring check on a much slower interval would be a good solution here, or to make the ability end no matter what after, say, ~10 seconds.

**Comment by RDaneliya** [comment]
I've tried various conditions and seems problem about movement_blocking. I've faced such issue only using forge.
Power loads normally but never finishes no matter what. I've tested in single player and multiplayer
I agree that new condition might not cover some cases but I think it's important that power should finish one way or another. 
I suggest to add this fix and refactor it later if it causes any problems.
Imo it's better than current state

**Comment by RDaneliya** [comment]
Just tested. Ability doesn't trigger on reaching not attached torch

**Comment by muon-rw** [comment]
Interesting. Thanks for testing it thoroughly - Will include this in a future update (though it may be awhile, currently on some other projects)

**Comment by RDaneliya** [comment]
Found one bug with current fix. Ability triggers player hits block with head. Will do further researches and try to make proper fix that covers other cases

**Pull request merged**
